databases:
  - name: avatar_app_production
    databaseName: avatar_app_production
    user: chima
    password: Aldus1024@
    plan: free

services:
  - type: web
    name: avatar
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh && bundle exec rails assets:precompile"
    startCommand: "bundle exec rails server -e production"
    envVars:
      - key: DATABASE_URL
        value: postgres://chima:Aldus1024@65.21.82.122/avatar_app_production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2