# Exported from Render on 2024-09-25T13:59:28Z
databases:
- name: mysite
  databaseName: mysite_xx8h
  user: mysite
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: mysite
  runtime: ruby
  repo: https://github.com/mauricio-chirino/avatar_app
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: mysite
      property: connectionString
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
